import cv2
img = cv2.imread("img/img1.jpg")
img1 = cv2.imread("img/img3.jpg")
img2 = cv2.imread("img/nick_memasik.png")
img3 = cv2.imread("img/img2.jpg")
cv2.imshow("bender",img)
cv2.waitKey(0)
cv2.imshow("bender",img1)
cv2.waitKey(0)
img2 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
cv2.imshow("bender",img2)
cv2.waitKey(0)
img3 = cv2.cvtColor(img3,cv2.COLOR_BGR2HSV)
cv2.imshow("bender",img3)
cv2.waitKey(0)
